Secure memory refactor
godaddy/asherah pull request #326
Opened 2020-10-17 04:35 UTC by jgowdy

This is the long awaited refactor of the poor abstractions of SecureMemory

2020-10-23 01:03 UTC, rleverence-gd requested changes

2020-10-23 01:03 UTC, rleverence-gd commented on csharp/SecureMemory/PlatformNative/SystemInterface.cs
> +                        throw new PlatformNotSupportedException("Unknown platform");
Put the platform in the exception message? It's available via `RuntimeInformation.OSDescription`

2020-10-23 01:03 UTC, rleverence-gd commented on csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/OpenSSL/OpenSSL11ProtectedMemoryAllocatorLP64.cs
> +            // Debug.WriteLine($"SetReadAccess: Rounding length {length} to nearest blocksize");
Commented out code

2020-10-23 01:03 UTC, rleverence-gd commented on csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/OpenSSL/OpenSSL11ProtectedMemoryAllocatorLP64.cs
> +            // TODO release unmanaged resources here
Is this a critical thing to have done in this PR?

2020-10-23 01:03 UTC, rleverence-gd commented on csharp/SecureMemory/SecureMemory/ProtectedMemoryImpl/Windows/WindowsProtectedMemoryAllocatorLLP64.cs
> +            /*
Commented out code.

2020-10-23 15:29 UTC, jgowdy commented
I think there's an issue here where I'm treating the IV field as an actual IV in OpenSSLCryptProtectMemory rather than the fact that in AEAD it's repurposed as a nonce field.  I think this class suffers from the dreaded nonce reuse for the same key issue.

2020-10-23 17:45 UTC, jgowdy commented on csharp/SecureMemory/PlatformNative/OpenSSL/OpenSSLCryptoWindows.cs
> +            // BUG: EVP_CIPHER_block_size returns 1
I've figured this out, and this actually isn't a bug.  With AEAD ciphers like GCM there is no padding which is why EVP_CIPHER_block_size returns 1 byte.  With AEAD, if you encrypt 2 bytes, you get 2 bytes, there's no rounding to the next block size like with CBC.

2020-10-23 18:31 UTC, jgowdy commented
Some block modes (like CBC) require the input to be split into blocks and the final block to be padded to the block size using a padding algorithm (e.g. add a special padding character). Other block modes (like CTR, CFB, OFB, CCM, EAX and GCM) do not require padding at all, because they perform XOR between portions of the plaintext and the internal cipher's state at each step.

2020-10-25 14:08 UTC, jgowdy commented
I'm changing direction on this

2020-10-25 14:08 UTC, closed without merging