Updated the dependencies in the csharp libraries
godaddy/asherah pull request #353
Opened 2021-03-24 22:39 UTC by sbos-godaddy

- Updated dependencies in the .NET Asherah projects to reduce likelihood of downstream dependency conflicts

2021-03-24 22:47 UTC, jgowdy approved these changes

2021-03-24 22:51 UTC, rohitjha approved these changes

2021-03-24 23:18 UTC, aka-bo requested changes
Please open a separate PR for the `SecureMemory` changes and I'll get that one pushed out ASAP. Once SecureMemory `v0.2.0` has deployed, the `Godaddy.Asherah.SecureMemory` package references will need to be updated accordingly.

2021-03-24 23:18 UTC, aka-bo commented on csharp/AppEncryption/Directory.Build.props
> +    <Version>0.3.0</Version>
moving forward, dependency updates will be treated as patch releases
```suggestion
    <Version>0.2.1</Version>
```

2021-03-25 15:38 UTC, sbos-godaddy commented
@aka-bo Created #354 to handle the SecureMemory changes.

2021-03-25 18:48 UTC, aka-bo approved these changes

2021-03-25 18:48 UTC, merged