Log KMS decrypt errors in Asherah Go
godaddy/asherah pull request #438
Opened 2022-07-24 14:46 UTC by dalibor

Useful to print the error before `continue`. I had to build `asherah-cobhan` binaries with patched Asherah Go to be able to detect the issue documented in https://github.com/godaddy/asherah-cobhan/pull/39.

2022-07-24 14:52 UTC, jgowdy commented
![Logo](https://user-images.githubusercontent.com/42570337/152954017-2101d077-2be7-48a8-8d34-618fe5a7c779.png)
**Checkmarx AST – Scan Summary & Details** – [46fe8788\-1e88\-47eb\-9abd\-8109d730efe1](https://ast.checkmarx.net/projects/df34b7f2-6257-4bd2-a1e0-ecf40b2777d3/scans?id=46fe8788-1e88-47eb-9abd-8109d730efe1&branch=print_kms_errors)
### No New Or Fixed Issues Found

2022-09-14 17:01 UTC, aka-bo requested changes

2022-09-14 17:01 UTC, aka-bo commented on go/appencryption/pkg/kms/aws.go
> +				log.Printf("error kms decrypt: %s", err)
Need to use [`Debugf`](https://github.com/godaddy/asherah/blob/a6c6eacc25a5b6a020b9f8e6242c090ced4ff7a6/go/appencryption/pkg/log/log.go#L18) from the internal `log` package to ensure these are only logged when debugging is enabled.

2022-09-14 17:01 UTC, aka-bo commented on go/appencryption/pkg/kms/aws.go
> +				log.Printf("error crypto decrypt: %s", err)
same here

2022-09-14 18:50 UTC, aka-bo approved these changes
LGTM

2022-09-14 18:50 UTC, merged